### PR TITLE
Console fix

### PR DESCRIPTION
**Pull request by JulianKoch**
The console now displays the full logs and scrolling is more performant. Ready for review.

### CODE REVIEW

**Comment by alexfupp** [comment]
reviewed, added tasks in alexfupp@dfd2446293a3d5a96fc10ea9c67911b4ec7d24f7

**Comment by JulianKoch** [comment]
Ready for next review.

**Comment by alexfupp** [comment]
reviewed, see new comments in alexfupp@d41c5f3da27ff38cb79315e6c6814ea695f1c003

**Comment by JulianKoch** [comment]
New Review please.

**Comment by JulianKoch** [comment]
New review for the sake of reviews please.

**Pull request merged**
