### PR TITLE
Add verify pin

### PR DESCRIPTION
**Pull request by JGoeke**
Finished the implementation and test creation of the VerifyPin functionality. Thereby the auto generated code of the PinManagement was replaced. Furthermore the function getApduSet was removed from the Protocol interface and all related classes.

### CODE REVIEW

**Comment by alexfupp** [comment]
reviewed, see comments in alexfupp@1b17d4b98e7b7775c3f09e5471174e5475ea722d

**Comment by JGoeke** [comment]
rdy for review

**Comment by JGoeke** [comment]
waiting for review

**Comment by alexfupp** [comment]
Reviewed, see alexfupp@57fa4d46fe087f64b5d5db5518f3d5c93b224c01

**Comment by JGoeke** [comment]
ready for review

**Comment by alexfupp** [comment]
Reviewed, see alexfupp@ecdd5eb45ca05925293a97fc8fae8b7e52f0b589

**Comment by JGoeke** [comment]
ready for review

**Comment by alexfupp** [comment]
reviewed, see alexfupp@3b15be4bd71363e93bc4f62162f25d5291c67493

**Comment by JGoeke** [comment]
ready for review

**Comment by JGoeke** [comment]
ready for review

**Pull request merged**
