### PR TITLE
Newtestcasesfor tlv length&primitive tlv data obect&constructed tlv data object

### PR DESCRIPTION
**Pull request by lukasstauffenberg**
added 9 new testcases for tlvlength
added testcases for primitivetlvdataobjec
added testcases for constructedtlvdata object
21.01 * added testcases for SecureMessaging

ready for review

### CODE REVIEW

**Comment by alexfupp** [comment]
- won't accept code that contains compiler warnings
- A more readable way to construct TLV- objects within unit tests would be the use of TlvDataObjectFactory.createTLVDataObject(String)

**Comment by lukasstauffenberg** [comment]
Hello, the warnings have been fixed 

ready for review

**Comment by lukasstauffenberg** [comment]
added new testcases for secstatus and Utils
Removed unused method in Utils

**Comment by alexfupp** [comment]
I added several comments ond alexfupp@fd354176e7ae12e09bf9a8a2c697c87a49446acb

**Comment by lukasstauffenberg** [comment]
Pullrequest closed:

Opened 2 new Pullrequest:

https://github.com/PersoSim/de.persosim.simulator/pull/64 - Testcases for 4 Classes

https://github.com/PersoSim/de.persosim.simulator/pull/63   - Utils

**Pull request closed without merging**
