### PR TITLE
Big integer fix(hexto byte&testcases)

### PR DESCRIPTION
**Pull request by lukasstauffenberg**
method in HexString.java has been modified

testcases for hexStringtest have been added.

### CODE REVIEW

**Comment by alexfupp** [comment]
reviewed, added some comments on alexfupp@7eff28544c10c2ba25f896eb7ba6ce02c29fdd32

**Comment by alexfupp** [comment]
reviewed, see my branch for modifications

**Comment by lukasstauffenberg** [comment]
Ready for review @ cd52b94304f5af3c7565c9d68e855818060d0ce7

**Comment by alexfupp** [comment]
reviewed, see my branch for task annotations

**Comment by lukasstauffenberg** [comment]
2 files modified 
ready for review

**Pull request merged**
