### PR TITLE
Utilstest branch: tests have been renamed

### PR DESCRIPTION
**Pull request by lukasstauffenberg**
This branch contains Utilstest.java
renamed all Testcases in UtilsTest

### CODE REVIEW

**Comment by alexfupp** [comment]
reviewed partly, see alexfupp@703c3b3

**Comment by lukasstauffenberg** [comment]
ready for review

**Comment by alexfupp** [comment]
reviewed, see alexfupp@ba4e9822d52c80f13379ea040e4493d3c5fa12d3

**Comment by lukasstauffenberg** [comment]
ready for review

**Comment by alexfupp** [comment]
reviewed, see alexfupp@4b6a3020359f1a75ce85941e51c16f47b879a5fb

**Comment by lukasstauffenberg** [comment]
ready for review

**Comment by alexfupp** [comment]
reviewd, much better, see alexfupp@4fb40e9e20b42408834876a3717b268f0a12f13f for remaining comments

**Comment by lukasstauffenberg** [comment]
ready for review

**Comment by alexfupp** [comment]
reviewed, see alexfupp@d8361dd8f316c89424f97256d06924f5f85dd9c3

**Comment by lukasstauffenberg** [comment]
ready for review

**Comment by lukasstauffenberg** [comment]
ready for review

**Pull request merged**
