### PR TITLE
Branch: Testcases for Primitive,Constructed,SecureMessaging,SecStatus

### PR DESCRIPTION
**Pull request by lukasstauffenberg**
All Testcases have been renamed
Few of them have been edited or removed cause of redundancy

### CODE REVIEW

**Comment by alexfupp** [comment]
reviewed, added some tasks already discussed offline see alexfupp@5a0d496f26a80edcd6dc7822cbb383241c41e83f

**Comment by alexfupp** [comment]
reviewed partly, see alexfupp@703c3b39b62489f3e4851c9345e20b1099d36324

**Comment by lukasstauffenberg** [comment]
Fixed tasks in ConstructedTlvDataObjectTest - Factory usage
Fixed tasks in PrimitiveTlvDataObjectTest - Factory usage
Fixed tasks in SecureMessagingTest - Exceptions

this branch includes tasks for UtilsTest.java, but for this there is a seperate branch where the tasks are beeing fixed

**Comment by alexfupp** [comment]
see alexfupp@47877fcf4afd8a4b3ddab1602d36538e99e21037

**Comment by lukasstauffenberg** [comment]
Ready for review

**Pull request merged**
